name: Deploy Helm Chart
permissions: read-all

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  helm_deploy:
      name: Deploy helm chart
      environment: ${{ inputs.environment }}
      runs-on: ubuntu-latest
      steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@d4fffb50872869abe2d9a9098a6d9c5aa7d16be4 # v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519 # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      
      - name: Setup WireGuard
        uses: nycmeshnet/nycmesh-vpn-action@main
        with:
          config-name: "ghelement"
          private-key: ${{ secrets.WG_PRIVATE_KEY }}
          server-preference: "3,10,11"
          test-ip: "10.10.10.10"

      - name: Render MAS SMTP config
        run: |
          cat <<'EOF' > mas-values.yaml
          matrixAuthenticationService:
            additional:
              auth.yaml:
                config: |
                  account:
                    password_registration_enabled: true
                    registration_token_required: false
                    password_registration_email_required: true
                    password_change_allowed: true
                    password_recovery_enabled: true
                    login_with_email_allowed: true
          
                  policy:
                    data:
                      admin_users:
                        - admin
                      emails:
                        allowed_addresses:
                          suffixes: ["@nycmesh.net"]
          
                  email:
                    from: '"Matrix Authentication Service" <mastodon@nycmesh.net>'
                    reply_to: '"No reply" <no-reply@matrix.nycmesh.net>'
                    transport: smtp
                    hostname: "${{ secrets.SMTP_HOST }}"
                    port: ${{ secrets.SMTP_PORT }}
                    username: "${{ secrets.SMTP_USERNAME }}"
                    password: "${{ secrets.SMTP_PASSWORD }}"
          EOF

      - name: Install Helm Chart
        run: |
          scp ${{ secrets.SSH_USER }}@${{ secrets.SSH_TARGET_IP }}:~/.kube/config ./
          helm upgrade \
            --install \
            --kubeconfig ./config \
            --kube-apiserver https://${{ secrets.SSH_TARGET_IP }}:6443 \
            --namespace "ess" \
            --create-namespace  \
            ess oci://ghcr.io/element-hq/ess-helm/matrix-stack \
            -f ./ess-config-values/hostnames.yaml \
            -f ./ess-config-values/tls.yaml \
            -f mas-values.yaml \
            --wait
